apiVersion: v1
kind: Service
metadata:
  name: udagram-frontend
  labels:
    run: udagram-frontend
spec:
  ports:
  - name: "8100"
    port: 8100
    targetPort: 8100
    protocol: TCP
  selector:
    run: udagram-frontend